[en]
title = "I'm Agustín"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[es]
title = "Blog Personal"
description = "Me puedes decir Tin"
contentDir = "content/spanish"
weight = 2
LanguageName = "ES"
