  [[main]]
  name = "Inicio"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Publicaciones"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portafolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Acerca de mi"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Logros"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "Certificados"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"

  [[main]]
  name = "Contactame"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"